trigger:
    - master

strategy:
    matrix:
        node_8:
            node_version: 8.x
        node_10:
            node_version: 10.x
        node_11:
            node_version: 11.x
        node_12:
            node_version: 12.x

pool:
    vmImage: 'Ubuntu-16.04'

steps:
    - task: NodeTool@0
      inputs:
          versionSpec: $(node_version)
    - script: npm install
      displayName: npm install
    - script: npm run test:fmt
      displayName: prettier
    - script: npm run test:lint
      displayName: eslint
    - script: npm run test:jest
      displayName: jest
    - script: npm run build
      displayName: build
